name: MullvadConfigs
version: 0.1.0.0
github: "sandydoo/MullvadConfigs"
license: BSD3
license-file: LICENSE
author: "Sander Melnikov"
maintainer: "Sander Melnikov <hey@sandydoo.me>"
copyright: "© 2020 Sander Melnikov"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/sandydoo/MullvadConfigs#readme>

ghc-options: -Wall
default-extensions:
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards

dependencies:
- name: base
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- aeson
- bytestring
- containers
- directory
- filepath
- http-conduit
- iproute
- lens
- lens-aeson
- name: relude
  mixin:
    - (Relude as Prelude)
- text
- zip

library:
  source-dirs: src

executables:
  create-mullvad-configs:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MullvadConfigs

tests:
  MullvadConfigs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MullvadConfigs
